replicaCount: 2
image:
  repository: testproject.azurecr.io/goapp
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
appMessage: "hello-world"

resources:
  requests:
    cpu: "50m"   
    memory: "64Mi"
  limits:
    cpu: "200m" 
    memory: "128Mi"

readinessProbe:
  path: /version
  port: 8080
  initialDelaySeconds: 2
  periodSeconds: 5
livenessProbe:
  path: /version
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

ingress:
  enabled: true                
  className: nginx              
  annotations:                 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: goapp.com
      paths:
        - path: /              
          pathType: Prefix   