replicaCount: 1
image:
  repository: testproject.azurecr.io/goapp
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
appMessage: "hello-world"
resources: {}

readinessProbe:
  path: /version
  port: 8080
  initialDelaySeconds: 2
  periodSeconds: 5
livenessProbe:
  path: /version
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5